# -*- coding: utf-8 -*-
"""IntroductionToPython

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fsSr3XKjdiorIWPp7b5QTQ06phcdG0Aa

# Exercises to get you used to Python syntax and data processing in Python

## Introduction to Python. If you're already familiar with basic Python syntax and data types, feel free to skip this section!

1.   Python Basics and Loops
2.   Lists and strings
3.   Functions and classes
4.   Other data structures
"""

#Python basics
#The first thing you need to understand about Python syntax is indentation matters! Unlike C++ or Java or JS, Python uses indentations as a way to differentiate lines and what functions/classes/conditionals certain lines belong to!

#No need to define data types before variables
a = 0
b = "Hello"
  #This line would give an error as it's indented for no reason
  #j = 1
  
#Quotes can be either single or double, it doesn't matter unlike C++
c = 'bye'
d = [10,15,20,25,30,35,40]
print(b,c)
print('\n')

#No need for semi colons. New lines mean a new statement. In addition, no need for curly braces. A colon represents the end of an if/else, for loop, while loop etc.
c = False
# c = True
#No need for parentheses around conditions either
if c == True:
  print("Hello")
else:
  print("Bye")


#Loops
print("\nFOR LOOP INDEX-BASED")
#For loop
#Equivalent C++ Syntax: for (int i = 0; i < d.size(); i++)
for i in range(0, len(d)):
  print(d[i])

print("\nFOR LOOP W/OUT INDEX")
#You can also loop without an index iterator
#Equivalent C++ Syntax: for (int val : d)
for val in d:
  print(val)

print("\nWHILE LOOP EX1")
#While loop
i = 0
#Effectively same as the first for loop.
while i < len(d):
  print(d[i])
  i += 1

print("\nWHILE LOOP EX2")
while len(d) > 0:
  #Deletes the last element of the list
  print(d.pop(-1))

# Lists (equivalent to a vectory in C++. Can be increased in size and decreased in size):
# Don't worry about arrays when dealing w/ python. Think of arrays and lists as the same thing unlike in C++ where arrays and vectors are different.
a = [1, 2, 3, 4, 5, 6]

# You can even have multiple data types in the same list although this is unadvisable.
lst = [1, "HELLO", True]
print(lst)

#Python is incredibly flexible in that you can just print a list and it'll print it all nicely. No more loops just to print a container!
print(a)

# get a list containing the last 3 elements of a. This is called splicing. The syntax is a[startIndex: endIndex + 1]. It'll get the values from the startIndex (inclusive) to the endIndex (non-inclusive)
b = a[3: 6]
# If you don't specify an end index to the splice, it'll assume you mean "go to the end of the list"
d = a[3:]
# Same goes for not specifying the start index. If you want to see what this returns, feel free to add a print statement!
e = a[:len(a)]

c = [10,9,8,7,6,5,4,3,2,1]
#sorted will sort c but won't change the initial value of c unless assigned back into c. 
print(sorted(c))

#Indexing works the same way
print(c[0])

# -1 index represents the LAST element. No need to do length - 1.
print(c[-1])

#len(c) is length of object
print(len(c))

#Strings
c = "HELLO!"
#First character of c
print(c[0])
intStr = "123"

#Casts intStr into an int
intVersion = int(intStr)

#Casts int into str
intStr = str(intVersion)

sentence = "-- Atlas Digital -- is better than -- Atlas Strategy --"
#Split is a very useful built-in function that can split a string by a delimiter. For example, the default delimiter is a space, meaning it'll create a list with each word based on spacing!
print(sentence.split())
#This would split the string by --
print(sentence.split("--"))

#Functions
#Defined with a def as the key word. Remember there's no need to type things, but if you'd like, Python 3.10.7 does support typing as shown below.

#This is ok
def atlasDigital(project1, project2):
  print("We have so many projects")

#This is also ok (if you have Python >3.10.7)
def atlasDigital(project1 : str, project2 : str) -> bool:
  print("This is really cool!")


# Classes
# One key note about python is that it supports functional programming. This means you don't have to encapsulate everything in a class unlike C++ or Java. 
# But it does also support Object Oriented Programming so if you'd like to create classes...

class Atlas:
  def __init__(self, param1):
    #This is the constructor. The function name is __init__ and for any function in the class, the first param must be "self".
    #To access/create member variables, use self.[member variable]
    self.projects = param1

  #Effectively, this member function has no parameters. self is just a way for the computer to know that this function is part of the Atlas class. 
  def func1(self):
    print(self.projects)
  

#To create an instance of a class w/ a passed in value for the constructor
umichAtlas = Atlas("CantooAI")
#To call a member variable
umichAtlas.func1();
#Loops

#Initialized with curly braces. You can also initialize it with key-value pairs.
dict = {}
filledDict = {"Hello":1, "Bye":2}

#To access a value of a dict, use the indexing syntax with the index as the key.
print(filledDict["Hello"])


#Dictionary keys. To convert it to a list, just cast it to a list
print(list(filledDict.keys()))

#To add a key-value pair...
filledDict["newKey"] = 3

if "newKey" in filledDict:
  print("newKey is a key")
else:
  print("It ain't a key.")

print(filledDict)

